version: "3.8"

services:
  eazybankdb:
    image: mysql:latest
    container_name: eazybankdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb  # This is needed for MySQL to start correctly
    ports:
      - "3307:3306"
    networks:
      - eazybank-network
    volumes:
      - eazybankdb_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d  # Runs SQL scripts at startup

  accountsms:
    image: mayukhsri1010/accounts
    container_name: accountsms
    ports:
      - "8080:8080"
    depends_on:
      - eazybankdb
    networks:
      - eazybank-network

  cardsms:
    image: mayukhsri1010/cards
    container_name: cardsms
    ports:
      - "8181:8181"
    depends_on:
      - eazybankdb
    networks:
      - eazybank-network

  loansms:
    image: mayukhsri1010/loans
    container_name: loansms
    ports:
      - "8282:8282"
    depends_on:
      - eazybankdb
    networks:
      - eazybank-network

networks:
  eazybank-network:
    name: eazybank-network  # Set a fixed name
    driver: bridge


volumes:
  eazybankdb_data:
